# Generated by Django 4.1.2 on 2022-10-23 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_date', models.DateField(default=datetime.datetime(2022, 10, 23, 5, 54, 13, 232343, tzinfo=datetime.timezone.utc))),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 10, 23, 5, 54, 13, 232367))),
                ('price', models.IntegerField(null=True)),
                ('coin', models.CharField(default='btc', max_length=256)),
            ],
        ),
    ]
