# Generated by Django 4.1.2 on 2022-10-23 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodatastore',
            name='processing_date',
            field=models.DateField(default=datetime.date(2022, 10, 23)),
        ),
        migrations.AlterField(
            model_name='cryptodatastore',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 6, 31, 42, 380502)),
        ),
    ]
