# Generated by Django 4.1.2 on 2022-10-23 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_check', '0002_alter_cryptodatastore_processing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodatastore',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryptodatastore',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 31, 51, 729145)),
        ),
    ]
